CREATE TABLE posts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    image_url VARCHAR(500),
    post_type VARCHAR(32) NOT NULL DEFAULT 'USER_POST', -- USER_POST, ANNOUNCEMENT, SYSTEM_MESSAGE
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE, HIDDEN, DELETED
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
); 